    version: "3.3"

    services:
      traefik:
        image: traefik:latest
        restart: always
        container_name: traefik
        ports:
          - "80:80" # <== http           
          - "443:443" # <== https
        command:
          - --api.insecure=no # <== On cadenace l'API
          - --api.dashboard=true # <== Activation du dashboard
          - --api.debug=true # <== Mode debug on
          - --log.level=DEBUG # <== Le level en mode debug est tres bavard
          - --providers.docker=true # <== Docker est le provider de traefik
          - --providers.docker.exposedbydefault=false # <== Tout nos containers ne seront pas necessairement expose a traefik
          - --providers.docker.network=web # <== Creation du network utilise par traefik et tout les docker sy connectant
          - --entrypoints.web.address=:80 # <== L entrypoint sur le port 80 nomme web
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock # 
          - $PWD/traefik.toml:/etc/traefik/traefik.toml # ATTENTION dans ce git il est dans un autre dossier, move le fichier 
          - $PWD/dynamic.toml:/etc/traefik/dynamic.toml # ATTENTION : N est NECESSAIRE UNIQUEMENT si vous jouez avec votre propre certificat, commenter si letsencrypt
          - $PWD/certs/:/etc/traefik/certs 
          - "/etc/timezone:/etc/timezone:ro" # meme timezone que l hote
          - "/etc/localtime:/etc/localtime:ro" #meme timezone que l hote
          
        networks:
          - web # <== Traefik est connecte a ce network, il faudra le creer avant le premier lancement
        labels:
          - "traefik.enable=true" # 
          - "traefik.http.routers.api.rule=Host(`mon.domain`)" # <== On definit le domaine
          - "traefik.http.routers.api.service=api@internal" # <== L api
          - "traefik.http.routers.api.middlewares=auth" # on active le middleware d authentification
          - "traefik.http.middlewares.auth.basicauth.users=mon_user:$mon_passwd" # definition login / passwd. Passez par htpasswd pour le gen. ! au premier "$" obligatoire
            
    networks:
      web:
        external: true
