    [api]
      dashboard = true
      insecure = true


    [entryPoints]
      [entryPoints.web]
        address = ":80"
        [entryPoints.web.http]
          [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
              to = "websecure"
              scheme = "https"
              permanent = true

      [entryPoints.websecure]
        address = ":443"
          [entryPoints.websecure.http.tls]

    [providers]
      [providers.file]
        filename = "/etc/traefik/dynamic.toml"
        watch = true

      [providers.docker]
        watch = true
        exposedByDefault = false
        network = "web"
